version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_1016_test499547Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_1016_test499547.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: Kvv_1016_test499547Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.kvv_1016_test499547.integrations:SIQAAdapterFlow
  packages:
  - name: Kvv_1016_test499547Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
